### ISSUE TITLE
Json is represented as  "type": "object"

### ISSUE THREAD

**Issue by capaj** [valentinpalkovic/prisma-json-schema-generator#303] opened 2022-01-25 11:12 UTC
It should be  generated as
```json
{         
  "anyOf": [
        { "type": "object" },
        {
          "type": "array"
        }
      ]
}
```

it is generated as 
```json
{"type": "object"}
```

**Comment by valentinpalkovic** [comment] 2022-01-25 14:53
@capaj ThanDo for reporting this! The Issue is resolved and should be fixed now :)

**Comment by capaj** [comment] 2022-01-25 15:37
@valentinpalkovic oh thank you for being able to jump on this so fast.

I just wish I had realized sooner, that a valid JSON is also saclar values like string, null or a number, so the generated type here should really be:

```json
 "type": ["number", "string", "boolean", "object", "array", "null"]
```

sorry for that. I mostly use graphql these days, so I forgot how to properly do `any` type in json schema.

**Comment by valentinpalkovic** [comment] 2022-01-25 15:58
No problem! :)

I just wanted to discuss with you, whether it makes sense to define the type without `null` for the case, that the JSON field is required!

Required case:
```
"type": ["number", "string", "boolean", "object", "array"]
```

Not required:
```
"type": ["number", "string", "boolean", "object", "array", "null"]
```

I know, that per definition the JSON type is allowed to also be `null`, but I would adjust this to conform to the user's expectation! If the user defines a JSON field as required, then `null` shouldn't be a valid value.

What do you think?

**Comment by capaj** [comment] 2022-01-25 17:25
yes, I do think null is to be expected.
I mainly use postgre as my DB and postgre will happily accept `null` and indeed we do use nulls in our Json fields in our production DB. So the generated schema should accept it too.

**Comment by valentinpalkovic** [comment] 2022-01-25 22:25
Alright! I will adjust my MR tomorrow and I will release a new version afterwards! I will let you know.

**Closed** 2022-01-26 08:02 UTC
Labels: released

**Comment by capaj** [comment] 2022-01-26 08:12
<img src="https://media3.giphy.com/media/xoV4JZ3cBaSGngdxxl/giphy.gif"/>
